[project]
name = "agentspractice"
version = "0.1.0"
description = "Agents for Chat completetion with tools"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=3.3.1",
    "requests>=2.34.2",
]

[project.scripts]
agentspractice = "agentspractice:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
